# Generated by Django 4.1.2 on 2022-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=30)),
                ('limitNum', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
