# Generated by Django 4.1.2 on 2022-12-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=30)),
                ('front', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bad_id_set', to='seater.student')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_set', to='seater.student')),
            ],
            options={
                'db_table': 'restriction',
            },
        ),
    ]
